### PR TITLE
Updated the commandline

### PR DESCRIPTION
**Pull request by DelusionalLogic**
New features:
Marking the song as downloaded
Making the song as being played
Better browser immitation

Changes:
Added the UserAgent back in
Added some comments
Added the header to the client specific feature list

### CODE REVIEW

**Comment by gsteph** [comment]
so does this actually stop them from banning you ?

**Comment by gsteph** [comment]
btw the commit says the whole file was changed. Maybe fix line endings in your editor ? I use the unix ones.

**Comment by DelusionalLogic** [comment]
It seems to be github for windows that forces the first commit to have changed everything.

msysgit is set up for unix style linendings. can i change it in github for windows?

I have not been banned yet.

**Comment by gsteph** [comment]
I'll accept and then deal with line endings later. Could you send me your groove.py somehow so that I can diff and actually see the changes ?

**Comment by gsteph** [comment]
Actually you don't need to. Github provides such a feature.

**Comment by gsteph** [comment]
Sorry xD turns out my files were the ones with CR LFs. You fixed them. Thanks.

**Comment by DelusionalLogic** [comment]
lol :P i saw that yours did this too when you commited with github for windows, it might do it by itself.

But everything is working great. wrote a quick script that downloaded 30 songs, everything is going strong, i have not been banned. so for now i'll consider that fixed :D

**Comment by gsteph** [comment]
Great! I'm merging.

**Comment by gsteph** [comment]
There's something I don't get.
removeSongsFromQueue() takes no parameters about the song itself. Is this intended ?
I'll trace the function and see.
EDIT: Yep. Weird.. I'll do some testing without the Queue stuff and see if I get banned. Because I'd like to minimize traffic.

**Comment by DelusionalLogic** [comment]
Yep, it grooveshark actually doesn't want any info about the song when they remove it, they just want to know what position of the queue it is in!

**Comment by DelusionalLogic** [comment]
I'm still getting banned, but it's completely random, it wasn't even close to when i was using the script. I have no idea why, but it's sporadic.

**Comment by gsteph** [comment]
I was going to say that too but I waited for more testing.

**Comment by DelusionalLogic** [comment]
I have no idea how they hand out the bans now. and as always, chrome is working just fine o.O

**Comment by gsteph** [comment]
That doesn't make sense. Sure you don't have some proxy enabled for chrome ?
Chrome uses IE's proxy settings so try IE too and see.

**Comment by DelusionalLogic** [comment]
i would notice if i used a proxy with chrome, i'm streaming, watching youtube, streaming music, and uploading, all with no lag. IE is broken too.

this is making no sense

EDIT:
Ofcourse, i'm logged in to chrome. still doesn't make any sense, but that is the only difference between all the browsers.

EDIT2:
I poked around in the sources, getStreamKeyFromSongIDEx is actually the more correct one, especially when we are only passing in one SongID

EDIT3:
Nope, i was wrong, being logged in did nothing at all D: just got strange again

EDIT4:
The strangeness is gone again, back to being banned in all borwsers, ohh well, at least it makes sense.

**Pull request merged**
