### PR TITLE
Some minor changes

### PR DESCRIPTION
**Pull request by yasoob**
I deleted the old readme because now we have a new one with markdown. Secondly I edited the email in the markdown. Previously the email linked to another page but now it is pointing correctly to mailto: .

### CODE REVIEW

**Comment by yasoob** [comment]
I have done it with a capital G.

**Comment by gsteph** [comment]
1) Small g please :D sorry.
2) Is there a way for that name commit to be merged with the md one? thing is.. it's a bit untidy this way

**Comment by yasoob** [comment]
1) Done
2) Done

Anything else ?

**Comment by gsteph** [comment]
Nope that's it. Thanks.

**Pull request merged**
